// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqv79otdqPpyR_jmVC-fuNp0-c0JuPYbc',
    appId: '1:337354080850:web:d0b67fda464609e3dd558b',
    messagingSenderId: '337354080850',
    projectId: 'flutterfireproject-91273',
    authDomain: 'flutterfireproject-91273.firebaseapp.com',
    storageBucket: 'flutterfireproject-91273.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDosSQUe1TPfh4ykLCy0oXZkSgh5g9FhCA',
    appId: '1:337354080850:android:3ca7f3433a5edb38dd558b',
    messagingSenderId: '337354080850',
    projectId: 'flutterfireproject-91273',
    storageBucket: 'flutterfireproject-91273.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-MdCrwEyEUP93O9iL980qQyw_ty3Qmxs',
    appId: '1:337354080850:ios:e177ec527e3e1489dd558b',
    messagingSenderId: '337354080850',
    projectId: 'flutterfireproject-91273',
    storageBucket: 'flutterfireproject-91273.appspot.com',
    iosClientId: '337354080850-c4u9bd7b9hf8c523pmgasar981i99f78.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfireproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-MdCrwEyEUP93O9iL980qQyw_ty3Qmxs',
    appId: '1:337354080850:ios:e177ec527e3e1489dd558b',
    messagingSenderId: '337354080850',
    projectId: 'flutterfireproject-91273',
    storageBucket: 'flutterfireproject-91273.appspot.com',
    iosClientId: '337354080850-c4u9bd7b9hf8c523pmgasar981i99f78.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfireproject',
  );
}
